# logging 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

# console 색상
spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB  # 전체 요청의 최대 크기 (여러 파일 포함 가능)
  output:
    ansi:
      enabled: always
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    async:
      request-timeout: 3000000  # 300초 (단위: 밀리초)


---
# 오류 처리
server:
  error:
    include-exception: true
    include-stacktrace: always

  #port 설정
  port: 8080

---
springdoc:
  swagger-ui:
    path: /api/v1/docs
    url: /openapi.json
  api-docs:
    path: /api/v1/api-docs